### ISSUE TITLE
Uncaught TypeError: Cannot read property 'onDidDestroy' of undefined

### ISSUE THREAD

**Issue by hisatoshi** [atom-minimap/minimap-cursorline#1]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.6.0-dev
**System**: Mac OS X 10.11.2
**Thrown From**: [minimap-cursorline](https://github.com/atom-minimap/minimap-cursorline) package, v0.1.0

### Stack Trace

Uncaught TypeError: Cannot read property 'onDidDestroy' of undefined

```
At /Users/yamazoehisatoshi/.atom/packages/minimap-cursorline/lib/minimap-cursorline-binding.js:28

TypeError: Cannot read property 'onDidDestroy' of undefined
    at MinimapCursorLineBinding.handleMarker (/Users/yamazoehisatoshi/.atom/packages/minimap-cursorline/lib/minimap-cursorline-binding.js:28:60)
    at /Users/yamazoehisatoshi/.atom/packages/minimap-cursorline/lib/minimap-cursorline-binding.js:17:14
    at TextEditor.module.exports.TextEditor.observeCursors (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:333:9)
    at new MinimapCursorLineBinding (/Users/yamazoehisatoshi/.atom/packages/minimap-cursorline/lib/minimap-cursorline-binding.js:14:40)
    at /Users/yamazoehisatoshi/.atom/packages/minimap-cursorline/lib/minimap-cursorline.js:40:23
    at /Users/yamazoehisatoshi/.atom/packages/minimap/lib/main.coffee:290:44
    at Map.forEach (native)
    at Main.observeMinimaps (/Users/yamazoehisatoshi/.atom/packages/minimap/lib/main.coffee:290:23)
    at Object.activatePlugin (/Users/yamazoehisatoshi/.atom/packages/minimap-cursorline/lib/minimap-cursorline.js:34:46)
    at Main.module.exports.PluginManagement.updatesPluginActivationState (/Users/yamazoehisatoshi/.atom/packages/minimap/lib/mixins/plugin-management.coffee:89:14)
    at /Users/yamazoehisatoshi/.atom/packages/minimap/lib/mixins/plugin-management.coffee:110:8
    at Config.module.exports.Config.observeKeyPath (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:612:7)
    at Config.module.exports.Config.observe (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:141:21)
    at Main.module.exports.PluginManagement.registerPluginControls (/Users/yamazoehisatoshi/.atom/packages/minimap/lib/mixins/plugin-management.coffee:109:49)
    at Main.module.exports.PluginManagement.registerPlugin (/Users/yamazoehisatoshi/.atom/packages/minimap/lib/mixins/plugin-management.coffee:42:6)
    at Object.consumeMinimapServiceV1 (/Users/yamazoehisatoshi/.atom/packages/minimap-cursorline/lib/minimap-cursorline.js:19:18)
    at Provider.module.exports.Provider.provide (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/service-hub/lib/provider.js:30:52)
    at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/service-hub/lib/service-hub.js:55:26
    at doNTCallback0 (node.js:419:9)
    at process._tickDomainCallback (node.js:389:13)
```

### Commands

```
     -2:23.7.0 emmet:insert-formatted-line-break-only (atom-text-editor.editor.is-focused)
     -2:23.7.0 editor:newline (atom-text-editor.editor.is-focused)
     -2:23.5.0 emmet:insert-formatted-line-break-only (atom-text-editor.editor.is-focused)
     -2:23.5.0 editor:newline (atom-text-editor.editor.is-focused)
     -0:49.9.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -0:47.3.0 core:confirm (atom-text-editor.editor.mini.is-focused)
```

### Config

```json
{
  "core": {
    "audioBeep": false,
    "disabledPackages": [
      "ide-haskell",
      "wrap-guide"
    ],
    "themes": [
      "cold-ui",
      "cold-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
atom-alignment, v0.12.1
autocomplete-modules, v1.3.1
autocomplete-paths, v1.0.2
autocomplete-python, v0.10.4
autocomplete-ruby, v0.1.0
cold-syntax, v1.3.0
cold-ui, v1.4.0
emmet, v2.3.14
file-icons, v1.6.12
highlight-line, v0.11.0
highlight-selected, v0.11.1
language-babel, v2.5.0
language-haskell, v1.5.1
language-javascript-jsx, v0.3.7
language-latex, v0.6.1
latexer, v0.2.7
linter, v1.11.2
linter-jshint, v1.2.1
minimap, v4.16.1
minimap-cursorline, v0.1.0
minimap-highlight-selected, v4.3.1
minimap-pigments, v0.1.7
node-debugger, v1.1.9
pigments, v0.19.0
react, v0.14.1
release-notes, v0.53.0
show-ideographic-space, v1.0.1
sync-settings, v0.6.0

# Dev
No dev packages
```

**Comment by fundon** [comment]
The latest stable version of atom is 1.8.0. So you need update it.
